services:
  nginx:
    restart: "always"
    image: "nginx_sprint_4"
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    restart: "always"
    image: "backend_sprint_4"
    container_name: backend
    env_file:
      - .env
    depends_on:
      - elasticsearch

  etl:
    restart: "always"
    image: "etl_sprint_4"
    container_name: etl
    volumes:
      - etl_data:/opt/etl/var/
    env_file:
      - .env
    depends_on:
      - postgres
      - elasticsearch

  redis:
    restart: "always"
    image: redis:7.0.5
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy allkeys-lru

  postgres:
    restart: "always"
    image: "postgres_sprint_4"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}

  elasticsearch:
    restart: "always"
    image: elasticsearch:8.5.1
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  postgres_data:
  elasticsearch_data:
  etl_data: