version: '3'
services:
  database:
      image: postgres:13.8-alpine3.16
      container_name: pg_database
      environment:
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
         - postgres_data:/var/lib/postgresql/pgdata/
      ports:
        - "5432:5432"
      env_file:
        - .env.dev
      networks:
        - practicum

  es_node:
     # alpine image not exit?
     image: elasticsearch:7.7.0
     container_name: elastic
     volumes:
       - es_data:/usr/share/elasticsearch/data
     environment:
           - discovery.type=single-node
     ports:
         - "9300:9300"
         - "9200:9200"
     networks:
       - practicum

  etl:
      container_name: etl_service
      build: etl
      restart: always
      volumes:
        - var_volume:/app/var/
      depends_on:
        - database
        - es_node
      env_file:
        - .env.dev
      networks:
        - practicum

networks:
  practicum:
    driver: bridge

volumes:
  postgres_data:
  var_volume:
  es_data: