openapi: 3.0.3
info:
  title: Authentication service
  description: Authentication service
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Development server
tags:
  - name: auth
    description: Authentication related operations
  - name: roles
    description: Operations with user roles
  - name: users
    description: User related operations
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Role:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    RolesList:
      type: array
      items:
        $ref: '#/components/schemas/Role'
    UserRegistrationRequest:
      type: object
      description: Data for registration of new user
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
    UserLoginRequest:
      type: object
      description: Data for login of existing user
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    ApiErrorResponse:
      type: object
      properties:
        msg:
          type: string
    TokensResponse:
      type: object
      required:
        - access_token
        - refresh_token
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
    LoginRecord:
      type: object
      required:
        - date
        - device
      properties:
        date:
          type: string
          format: date
        device:
          type: string
    LoginRecordList:
      type: array
      items:
        $ref: '#/components/schemas/LoginRecord'
    User:
      type: object
      required:
        - email
        - name
      properties:
        email:
          type: string
        name:
          type: string
  responses:
    200-PairOfTokens:
      description: Response with access and refresh token
      headers:
        Set-Cookie:
          description: refresh token in cookie
          schema:
            type: string
        WWW-Authenticate:
          description: access token
          schema:
            type: string
      # TODO убрать токены? для браузера куки и заголовки
      content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokensResponse'
    400-BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    401-Unauthorized:
      description: Invalid or missing access token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
    404-NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'
  parameters:
    UserIdParam:
      name: user_id
      in: path
      description: UUID of user
      required: true
      schema:
        type: string
        format: uuid
    RoleIdParam:
      name: role_id
      in: path
      description: UUID of role
      required: true
      schema:
        type: string
        format: uuid
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Log in user, get access and refresh tokens
      description: Log in user, get access and refresh tokens
      operationId: login
      requestBody:
        description: Login data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          $ref: '#/components/responses/200-PairOfTokens'
        '400':
          $ref: '#/components/responses/400-BadRequest'
  /auth/logout:
    post:
      tags:
        - auth
      summary: Log out user
      description: Log out user
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Succesful operation
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
  /auth/refresh:
    post:
      tags:
        - auth
      summary: Get new access and refresh tokens
      description: Get new access and refresh tokens
      operationId: refresh
      parameters:
        - in: cookie
          name: JWT_REFRESH_COOKIE_NAME # TODO добавить ключ в конфиг фласка
          schema:
            type: string
      # TODO добавить requestBody (для мобильных приложений)
      responses:
        '200':
          $ref: '#/components/responses/200-PairOfTokens'
        '400':
          $ref: '#/components/responses/400-BadRequest'
  /roles:
    get:
      tags:
        - roles
      summary: Get list of all roles
      description: Get list of all roles
      operationId: get_roles
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesList'
    post:
      tags:
        - roles
      summary: Create a new role
      description: Create a new role
      operationId: create_role
      requestBody:
        description: Data for creating a new role
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        '201':
          description: A new role created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400-BadRequest'
  /roles/{role_id}:
    parameters:
      - $ref: '#/components/parameters/RoleIdParam'
    get:
      tags:
       - roles
      summary: Get role by id
      description: Get role by id
      operationId: get_role
      responses:
        '200':
          description: An existing role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
    put:
      tags:
       - roles
      summary: Update role
      description: Update role
      operationId: update_role
      requestBody:
        description: Data for updating role
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Role updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
    delete:
      tags:
        - roles
      summary: Delete role
      description: Delete role
      operationId: delete_role
      responses:
        '200':
          description: Role deleted
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
  /users:
#     get:
#       # TODO добавить пагинацию
#       tags:
#         - users
#       summary: Get list of all users
#       description: Get list of all roles
#       operationId: get_users
#       responses:
#         '200':
#           description: Successful operation
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/UsersList'
    post:
      tags:
        - users
      summary: Register new user
      description: Register new user
      operationId: create_user
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          $ref: '#/components/responses/400-BadRequest'
  /users/{user_id}:
    parameters:
      - $ref: '#/components/parameters/UserIdParam'
    get:
      tags:
       - users
      summary: Get user by id
      description: Get user by id
      operationId: get_user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: An existing role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
    put:
      tags:
       - users
      summary: Update user
      description: Update user
      operationId: update_user
      security:
        - bearerAuth: []
      requestBody:
        description: Data for updating user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
    delete:
      tags:
        - users
      summary: Delete user
      description: Delete user
      operationId: delete_user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User deleted
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
  /users/{user_id}/roles:
    parameters:
      - $ref: '#/components/parameters/UserIdParam'
    get:
      tags:
        - users
      summary: Get list of user roles
      description: Get list of user roles
      operationId: get_user_roles
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesList'
  /users/{user_id}/roles/{role_id}:
    parameters:
      - $ref: '#/components/parameters/RoleIdParam'
      - $ref: '#/components/parameters/UserIdParam'
    post:
      tags:
        - users
      summary: Add a role to user
      description: Add a role to user
      operationId: add_user_role
      responses:
        '201':
          description: A role added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400-BadRequest'
    delete:
      tags:
        - users
      summary: Remove role from user
      description: Remove role from user
      operationId: delete_user_role
      responses:
        '200':
          description: Role deleted
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '404':
          $ref: '#/components/responses/404-NotFound'
  /users/{user_id}/login-history:
    parameters:
      - $ref: '#/components/parameters/UserIdParam'
    get:
      tags:
        - users
      summary: Get login history
      description: Get login history
      operationId: login_history
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of login records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRecordList'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
